export const LOGIN_USER = 'LOGIN_USER',
    LOGOUT_USER = 'LOGOUT_USER',
    GET_USERS = 'GET_USERS',
    GET_USER = 'GET_USER',
    LIMPAR_USERS = 'LIMPAR_USERS',
    LIMPAR_USER = 'LIMPAR_USER',

    GET_MSG_CONTATOS = 'GET_MSG_CONTATOS',
    GET_MSG_CONTATO = 'GET_MSG_CONTATO',
    LIMPAR_MSG_CONTATOS = 'LIMPAR_MSG_CONTATOS',
    LIMPAR_MSG_CONTATO = 'LIMPAR_MSG_CONTATO',

    GET_SOBRES = 'GET_SOBRES',
    GET_SOBRE = 'GET_SOBRE',
    LIMPAR_SOBRES = 'LIMPAR_SOBRES',
    LIMPAR_SOBRE = 'LIMPAR_SOBRE',

    GET_CONTATO = 'GET_CONTATO',
    LIMPAR_CONTATO = 'LIMPAR_CONTATO',

    GET_RODAPE = 'GET_RODAPE',
    LIMPAR_RODAPE = 'LIMPAR_RODAPE',

    GET_HOME = 'GET_HOME',
    LIMPAR_HOME = 'LIMPAR_HOME',
    GET_HOME_TOPO = 'GET_HOME_TOPO',
    LIMPAR_HOME_TOPO = 'LIMPAR_HOME_TOPO',
    GET_HOME_SERV = 'GET_HOME_SERV',
    LIMPAR_HOME_SERV = 'LIMPAR_HOME_SER',
    GET_HOME_ACAO = 'GET_HOME_ACAO',
    LIMPAR_HOME_ACAO = 'LIMPAR_HOME_ACAO',
    GET_HOME_DET = 'GET_HOME_DET',
    LIMPAR_HOME_DET = 'LIMPAR_HOME_DET',

    GET_HOME_TOPO_IMG = 'GET_HOME_TOPO_IMG',
    LIMPAR_HOME_TOPO_IMG = 'LIMPAR_HOME_TOPO_IMG',

    GET_HOME_ACAO_IMG = 'GET_HOME_ACAO_IMG',
    LIMPAR_HOME_ACAO_IMG = 'LIMPAR_HOME_ACAO_IMG',
    
    GET_HOME_DET_IMG = 'GET_HOME_DET_IMG',
    LIMPAR_HOME_DET_IMG = 'LIMPAR_HOME_DET_IMG',

    GET_SEOS = 'GET_SEOS',
    GET_SEO = 'GET_SEO',
    LIMPAR_SEOS = 'LIMPAR_SEOS',
    LIMPAR_SEO = 'LIMPAR_SEO';